version: "3.7"
services:

  db:
    image: postgres:12.4
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: Kageshimasu
      POSTGRES_PASSWORD: Kageshimasu
      POSTGRES_DB: crowlizer_db
    networks:
      - db_network

  admin:
      image: dockage/phppgadmin
      depends_on: 
        - db
      environment: 
        PHP_PG_ADMIN_SERVER_HOST: db
        PHP_PG_ADMIN_SERVER_DEFAULT_DB: crowlizer_db
      # ports:
      #   - 9000:80
      networks:
        - db_network

  django:
    build: ./backend/
    command: bash -c "python manage.py migrate && uwsgi --socket :8001 --wsgi-file config/wsgi.py"
    environment: 
        DB_HOST: db
        DB_PORT: 5432
    stdin_open: true
    depends_on:
      - db
    networks:
      - nginx_network
      - db_network
  
  app:
    build: ./frontend/
    depends_on:
      - django
    networks:
      - nginx_network

  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
      - django
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
