version: "3.7"
services:

  dbms:
    image: postgres
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: Kageshimasu
      POSTGRES_PASSWORD: sr87ojav
      POSTGRES_DB: crowlizer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432

  admin:
      image: dockage/phppgadmin
      depends_on: 
        - dbms
      # volumes:
      #   - ./.postgres/database:/usr/share/phppgadmin/classes/database
      environment: 
        PHP_PG_ADMIN_SERVER_HOST: dbms
        PHP_PG_ADMIN_SERVER_DEFAULT_DB: crowlizer_db
      ports:
        - 9000:80
